# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

submodules:
  include: all

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# poetry export --dev -f requirements.txt --output docs/requirements.txt
python:
  install:
    - requirements: docs/requirements.txt

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.8"
    nodejs: "16"
  jobs:
    post_install:
      # Install dependencies defined in your ``package.json``
      - npm ci
      # Install any other extra dependencies to build the docs
      - npm install -g jsdoc
